### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by Meli-0xFF**
Signed-off-by: Martin Melichercik martin.melichercik@gmail.com
done

### CODE REVIEW

**Comment by gkaretka** [comment]
Please remove **pychache** directories.

**Comment by Meli-0xFF** [comment]
done

**Comment by magic-sudo** [comment]
Please remove __pychache__ from all directories.
- modules

**Comment by gkaretka** [comment]
Please remove **pycache** from all directories.
- modules

**Comment by Meli-0xFF** [comment]
done

**Pull request merged**
